export * from './NFTCard';
export * from './Collections';
export * from './Contact';
export * from './Footer';
export * from './Header';
export * from './Landing';
export * from './Drops';
export * from './Categories';
export * from './CNav';
export * from './Settings';
export * from './DropdownComp';
export * from './Profile';
// export * from './Sidebar';
