import { Row, Stack } from 'react-bootstrap';
import BootstrapSwitchButton from 'bootstrap-switch-button-react';

const SecuritySetting = () => {
  return (
    <>
      <h1>Security Setting</h1>
      <Row>
        <Stack direction="horizontal" gap={2}>
          <h2>Enable 2-Factor Authentication</h2>
          <BootstrapSwitchButton checked={true} onChange={() => console.log('change')} size="xs" />
        </Stack>
        <p style={{ maxWidth: '650px' }}>
          Setting up 2-Factor Authentication (2FA) provides an additional layer of security to your
          account. With 2FA enabled, you will have to provide the code generated by your
          authenticator app to perform certain actions.
        </p>
      </Row>
    </>
  );
};

export { SecuritySetting };
